#!/bin/bash

pull_cache="$HOME/.cache/github-rofi/pulls.json"

cd "$(dirname "$(readlink "${BASH_SOURCE[0]}")")" || exit 1
./update_cache.sh

hit=$(
    (
        jq --from-file pulls_to_names.jq --raw-output < "$pull_cache" && \
        echo "refresh"
    ) | rofi -width 70 -dmenu -theme Arc-Dark -i)
if [ -z "$hit" ]; then
    exit 0
fi
if [ "$hit" == "refresh" ]; then
    ./update_cache.sh --force
    exit 0
fi
PR="${hit%%:*}"
xdg-open "https://github.com/$PR"
