#!/bin/bash

pull_cache="$HOME/.cache/github-rofi/pulls.json"

cd "$(dirname "$(readlink "${BASH_SOURCE[0]}")")" || exit 1
./update_cache.sh

rows() {
    jq --from-file pulls_to_branches.jq --raw-output < "$pull_cache" | \
    while read -r repo pr branch title; do
        printf "%-26s [%4d] %-26s %s\n" "$repo" "$pr" "$branch" "$title"
    done
}

hit=$(
    (
        rows && \
        echo "refresh"
    ) | rofi -width 70 -dmenu -theme Arc-Dark -i)
if [ -z "$hit" ]; then
    exit 0
fi
if [ "$hit" == "refresh" ]; then
    ./update_cache.sh --force
    exit 0
fi

set -x

[[ $hit =~ ([^/]+)/([^[:space:]]+)[[:space:]]+\[([0-9]+)\][[:space:]]+([^[:space:]]+) ]]

owner="${BASH_REMATCH[1]}"
repo="${BASH_REMATCH[2]}"
# pr="${BASH_REMATCH[3]}"
branch="${BASH_REMATCH[4]}"

./worktree.sh github.com "$owner" "$repo" "$branch"
