#!/bin/bash

pull_cache="$HOME/.cache/github-rofi/pulls.json"

cd "$(dirname "$(readlink "${BASH_SOURCE[0]}")")" || exit 1
./update_cache.sh

rows() {
    jq --from-file pulls_to_branches.jq --raw-output < "$pull_cache" | \
    while read -r repo pr branch title; do
        printf "%-26s [%4d] %-26s %s\n" "$repo" "$pr" "$branch" "$title"
    done
}

hit=$(
    (
        rows && \
        echo "refresh"
    ) | rofi -width 70 -dmenu -theme Arc-Dark -i)
if [ -z "$hit" ]; then
    exit 0
fi
if [ "$hit" == "refresh" ]; then
    ./update_cache.sh --force
    exit 0
fi

set -x

[[ $hit =~ ([^/]+)/([^[:space:]]+)[[:space:]]+\[([0-9]+)\][[:space:]]+([^[:space:]]+) ]]

owner="${BASH_REMATCH[1]}"
repo="${BASH_REMATCH[2]}"
# pr="${BASH_REMATCH[3]}"
branch="${BASH_REMATCH[4]}"

get_folder() {
    owner="$1"
    repo="$2"

    echo "$HOME/code/$owner/$repo"
}

get_worktree() {
    owner="$1"
    repo="$2"
    branch="$3"

    repo_dir="$(get_folder "$owner" "$repo")"
    worktree="${branch//\//-}"

    echo "$repo_dir.$worktree"
}

repo_dir="$(get_folder "$owner" "$repo")"

initfile=$(mktemp --suffix github-pr-init)
trap 'rm "$initfile"' EXIT

cat << EOF > "$initfile"
#!/bin/bash
( # run all git setup in a subshell to be able to exit on error
set -euo pipefail
EOF
chmod +x "$initfile"

if ! [ -d "$repo_dir" ]; then
    cat << EOF >> "$initfile"
# Can't find repository, cloning git@github.com/$repo into $repo_dir
echo + git clone "git@github.com:$owner/$repo" "$repo_dir"
git clone "git@github.com:$owner/$repo" "$repo_dir"
EOF
fi

worktree_dir="$(get_worktree "$owner" "$repo" "$branch")"

if ! git -C "$repo_dir" show-ref --verify --quiet "refs/remotes/origin/$branch"; then
    cat << EOF >> "$initfile"
# Remote branch doesn't exist, fetching..
echo + git -C "$repo_dir" fetch origin
git -C "$repo_dir" fetch origin
EOF
fi

if ! [ -d "$worktree_dir" ]; then
    cat << EOF >> "$initfile"
# No worktree exists, creating it..
if git -C "$repo_dir" rev-parse --quiet --verify "$branch" > /dev/null; then
  echo + git -C "$repo_dir" worktree add --guess-remote "$worktree_dir" "$branch"
  git -C "$repo_dir" worktree add --guess-remote "$worktree_dir" "$branch"
else
  echo + git -C "$repo_dir" worktree add --track -b "$branch" "$worktree_dir" "origin/$branch"
  git -C "$repo_dir" worktree add --track -b "$branch" "$worktree_dir" "origin/$branch"
fi
EOF
fi

cat << EOF >> "$initfile"
echo + git -C "$repo_dir" fetch origin "$branch"
git -C "$repo_dir" fetch origin "$branch"
)

# load files normally loaded without --rcfile
. /etc/bash.bashrc
. ~/.bashrc
if [ -d "$worktree_dir" ]; then
    cd "$worktree_dir"
else
    cd "$repo_dir"
fi
EOF

kitty bash --rcfile "$initfile"
